### PR TITLE
DeviceData: add property value conversion

### LINKED ISSUE #12: Dashboard fails to display a properties interface
## Steps to riproduce
Interface:
```json
{
    "interface_name": "com.rbino.InterfacciaPazza",
    "version_major": 0,
    "version_minor": 1,
    "type": "properties",
    "ownership": "device",
    "mappings": [
        {
            "endpoint": "/cose",
            "type": "string",
            "allow_unset": true
        }
    ]
}
```
I've published the string `"aaaaaaa"` on path `/cose`.
## Result
Going in the interface page in the device page this error is shown
2020-01-14-115138_2251x313_scrot
Data is correctly shown with `astartectl appengine devices data-snapshot`.

### PR DESCRIPTION
**Pull request by Pavinati**
Property values are not wrapped in a "value" field
Fix #12

Signed-off-by: Mattia Pavinati <mattia.pavinati@ispirata.com>

### CODE REVIEW

File: src/elm/Types/DeviceData.elm [hunk 1]
```diff
@@ -68,13 +68,26 @@ treeDecoder : Decoder (Dict String TreeNode)
...
 
 
+datastreamValueDecoder : Decoder TreeNode
+datastreamValueDecoder =
+    Decode.map2 Leaf
+        (Decode.field "value" AstarteValue.decoder)
+        (Decode.field "reception_timestamp" Iso8601.decoder)
+
+
+propertValueDecoder : Decoder TreeNode
```
Comment (rbino) [inline src/elm/Types/DeviceData.elm]: typo
